/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.niraj.bank;

/**
 *
 * @author Dell
 */
public class BankApp extends javax.swing.JFrame {
    BankControllerInterface bc;
    /**
     * Creates new form BankApp
     */
    public BankApp() {
        initComponents();
        bc = new BankControllerMYSQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jNewAccountMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        newAccountMenu = new javax.swing.JMenuItem();
        deleteAccountMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        allAccountsViewMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        withdrawMenu = new javax.swing.JMenuItem();
        depositMenu = new javax.swing.JMenuItem();
        fundTransferMenu = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CORE BANKING SYSTEM");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jNewAccountMenu.setText("File");

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jNewAccountMenu.add(exitMenu);

        jMenuBar1.add(jNewAccountMenu);

        jMenu2.setText("Account");

        newAccountMenu.setText("New Account");
        newAccountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountMenuActionPerformed(evt);
            }
        });
        jMenu2.add(newAccountMenu);

        deleteAccountMenu.setText("Delete Account");
        deleteAccountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountMenuActionPerformed(evt);
            }
        });
        jMenu2.add(deleteAccountMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        allAccountsViewMenu.setText("All Accounts");
        allAccountsViewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allAccountsViewMenuActionPerformed(evt);
            }
        });
        jMenu3.add(allAccountsViewMenu);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Transaction");

        withdrawMenu.setText("Withdraw");
        withdrawMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawMenuActionPerformed(evt);
            }
        });
        jMenu1.add(withdrawMenu);

        depositMenu.setText("Deposit");
        jMenu1.add(depositMenu);

        fundTransferMenu.setText("Fund Transfer");
        jMenu1.add(fundTransferMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMenuActionPerformed

    private void deleteAccountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAccountMenuActionPerformed

    private void newAccountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountMenuActionPerformed
        // TODO add your handling code here:
        NewAccountWindow naw = new NewAccountWindow(bc);
        this.add(naw);
        naw.setVisible(true);
    }//GEN-LAST:event_newAccountMenuActionPerformed

    private void withdrawMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawMenuActionPerformed
        // TODO add your handling code here:
        WithDrawAccountWindow wdaw = new WithDrawAccountWindow(bc);
        
        this.add(wdaw);
        wdaw.setVisible(true);
    }//GEN-LAST:event_withdrawMenuActionPerformed

    private void allAccountsViewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allAccountsViewMenuActionPerformed
        // TODO add your handling code here:
        ListAllAccounts laa = new ListAllAccounts(bc);
        this.add(laa);
        laa.setVisible(true);
    }//GEN-LAST:event_allAccountsViewMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem allAccountsViewMenu;
    private javax.swing.JMenuItem deleteAccountMenu;
    private javax.swing.JMenuItem depositMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenuItem fundTransferMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jNewAccountMenu;
    private javax.swing.JMenuItem newAccountMenu;
    private javax.swing.JMenuItem withdrawMenu;
    // End of variables declaration//GEN-END:variables
}
